fix find orphaned adoc script

diff --git a/bin/find-orphaned-adoc-files b/bin/find-orphaned-adoc-files
--- a/bin/find-orphaned-adoc-files
+++ b/bin/find-orphaned-adoc-files
@@ -4,212 +4,240 @@
 # This script checks which .adoc files are possibly orphaned.
 #
 
-MANUAL_NAME=
 AVAILABLE_MANUALS=( admin developer user )
+NAV_FILENAME="nav.adoc"
+PARTIALS_NAME="_partials"
+FAMILY='{partialsdir}'
+#FAMILY="partial$"
+MANUAL_NAME=
+PARTIAL_FILES=()
+PAGES_FILES=()
+PAGES_DIR=
+PARTIALS_DIR=
+NAV_FILE=
 
 function get_antora_nav_list()
 {
-    local filename="$1"
+	local filename="$1"
 
-    while read line; do
-        if [[ ${line} =~ \]$ ]]; then
-            revised_line=$(echo "$line" | sed 's/xref://' | sed 's/\[.*\]//g' | sed -r 's/^\*{1,} //')
-            echo "${revised_line}"
-        fi
-    done < "${filename}"
+	while read line; do
+		if [[ ${line} =~ \]$ ]]; then
+			# remove xref, the level (*), the description ([]), the manual-name
+			revised_line=$(echo "$line" | sed 's/xref//' | sed 's/\[.*\]//g' | sed -r 's/^\*{1,} //' | sed -E 's/^:.*?://')
+			echo "${revised_line}"
+		fi
+	done < "${filename}"
 }
 
 function validate_manual()
 {
-    # make a comma-separated list of the modules
-    local list=$(echo ${AVAILABLE_MANUALS[@]} | sed -r 's/[ ]+/, /g')
-    local manual="$1"
+	# make a comma-separated list of the modules
+	local list=$(echo ${AVAILABLE_MANUALS[@]} | sed -r 's/[ ]+/, /g')
+	local manual="$1"
 
-    # ok if manual is in the list of possible manuals
-    if [[ ${AVAILABLE_MANUALS[@]} =~ (^|[[:space:]])"${manual}"($|[[:space:]]) ]]; then
-       return 0
-    fi
+	# ok if manual is in the list of possible manuals
+	if [[ ${AVAILABLE_MANUALS[@]} =~ (^|[[:space:]])"${manual}"($|[[:space:]]) ]]; then
+	   return 0
+	fi
 
-    echo
-    echo "[${manual}] is not a valid manual." 
-    echo "Available manuals are: ${list}."
-    echo
-    exit
+	echo
+	echo "[${manual}] is not a valid manual." 
+	echo "Available manuals are: ${list}."
+	echo
+	exit
 }
 
 function usage()
 {
-    # create a list of modules separated by |
-    local list=$(echo ${AVAILABLE_MANUALS[@]} | sed -r 's/[ ]+/|/g')
+	# create a list of modules separated by |
+	local list=$(echo ${AVAILABLE_MANUALS[@]} | sed -r 's/[ ]+/|/g')
 
-    echo
-    echo "Usage: ./bin/find-orphaned-adoc-files [-h] [-n <${list}>]"
-    echo
-    echo "-h ... Help"
-    echo "-n ... Check manual <name>"
-    echo
-    echo "Files not added by its proper path like ../file.adoc"
-    echo "are reported as false positives !"
+	echo
+	echo "Usage: ./bin/find-orphaned-adoc-files [-h] [-n <${list}>]"
+	echo
+	echo "-h ... Help"
+	echo "-n ... Check manual <name>"
+	echo
+	echo "Note, files not added by its proper path like ../file.adoc"
+	echo "are reported as false positives !"
 }
 
 function find_orphans()
 {
-    validate_manual "$MANUAL_NAME" 
-    find_orphans_for_manual "$MANUAL_NAME"
+	validate_manual "$MANUAL_NAME"
+
+	# define the global variables
+	BASE_DIR="./modules/${MANUAL_NAME}_manual"
+	PAGES_DIR="${BASE_DIR}/pages"
+	NAV_FILE="${PAGES_DIR}/${PARTIALS_NAME}/nav.adoc"
+	# the partials dir may change to base_dir/partials_name
+	PARTIALS_DIR="${PAGES_DIR}/${PARTIALS_NAME}"
+
+	# get content for all partials but exclude the nav file, however we call it
+	# partials directory may not be present
+	if [ -d "${PARTIALS_DIR}" ]; then
+		PARTIAL_FILES=($(find "${PARTIALS_DIR}" -type f \( -name '*.adoc' ! -name ${NAV_FILENAME} \) -print | sed "s|$PARTIALS_DIR\/||g" | sort))
+		#echo "${PARTIAL_FILES[@]}" | tr ' ' '\n'
+		#exit
+	fi
+
+	find_orphans_for_manual "$MANUAL_NAME"
 }
 
 function find_orphans_for_manual()
 {
-	local found=
-	local base_dir="./modules/${MANUAL_NAME}_manual"
-	local pages_dir="${base_dir}/pages"
-	local nav_file="${base_dir}/nav.adoc"
-	local partials_dir="_partials"
-	local not_in_path='( -path "**/.DS_Store" -o -path "**/vendor" -o -path "**/.gitkeep" ) -prune -o'
+	local not_in_path='-path "**/.DS_Store" -o -path "**/vendor" -o -path "**/.gitkeep"'
+	local files_with_relative_include=()
+	local nav_list=()
+	local not_in_nav=()
+	local not_in_nav_filename_only=()
+	local includes_found=()
+	local true_not_in_nav=()
+	local search_list=()
+	local xrefed=()
+	local not_xrefed=()
+	local partial_list=()
+	local not_partial=()
 
-    echo
+	echo
 	echo "Finding orphans in the ${MANUAL_NAME} manual"
 	echo
 
-	# get a list of all .adoc files
-	all_files=($(find "$pages_dir" ${not_in_path} -type f -name '*.adoc' -print | sed "s|$pages_dir\/||g" |  sort))
-	#echo "${all_files[@]}" | tr ' ' '\n'
-
-	# _partials may not be present
-	partial_files=()
-	if [ -d "$pages_dir/$partials_dir" ]; then
-		partial_files=($(find "$pages_dir/$partials_dir" ${not_in_path} -type f -name '*.adoc' -print | sed "s|$pages_dir\/||g" | sort))
-		#echo "${partial_files[@]}" | tr ' ' '\n'
-	fi
-
-	# create an array diff of uniqe files without partials
+#	# get a list of all .adoc files but exclude the partials dir
 	# this list starts with _partial - needs later removal when checking
-	not_partial_files=($(echo ${all_files[@]} ${partial_files[@]} | tr ' ' '\n' | sort | uniq -u))
-	#echo "${not_partial_files[@]}" | tr ' ' '\n'
+	PAGES_FILES=($(find "${PAGES_DIR}" -type d \( -path "${PARTIALS_DIR}" -o $not_in_path \) -prune -o -type f \( -name '*.adoc' \) -print | sort | sed "s|${PAGES_DIR}/||"))
+	#echo "${PAGES_FILES[@]}" | tr ' ' '\n'
+	#exit
 
-	# get all files which have an include statement
-	# this is necessary because includes do have a relative path which needs further processing
-	# to remove false positives. the result includes the relative path of the files 
-	files_with_include=($(grep -oF 'include::./' "${not_partial_files[@]/#/$pages_dir/}" | sed "s|:include::.\/||g" | sort | uniq))
-	#echo "${files_with_include[@]}" | tr ' ' '\n'
+	# get all files which have a relative include statement
+	# (include a file relative the current adoc file)
+	# this is necessary because these includes need further processing to remove false positives.
+	# the result includes the relative path of the files
+	files_with_relative_include=($(grep -oF 'include::./' "${PAGES_FILES[@]/#/${PAGES_DIR}/}" | sed "s|:include::.\/||g" | sort | uniq))
+	#echo "${files_with_relative_include[@]}" | tr ' ' '\n'
+	#exit
 
-	# get all files referenced in the navigation file
-	nav_list=(`get_antora_nav_list "$nav_file"`)
+	# get all files referenced via xref in the navigation file
+	nav_list=(`get_antora_nav_list "$NAV_FILE"`)
 	#echo "${nav_list[@]}" | tr ' ' '\n'
+	#exit
 
-	# create an array diff of uniqe files not in nav w/o partials as they are never in the nav
-	not_in_nav=($(echo ${not_partial_files[@]} ${nav_list[@]} | tr ' ' '\n' | sort | uniq -u))
+	# create an array diff of uniqe files not referenced in the navigation
+	not_in_nav=($(echo ${PAGES_FILES[@]} ${nav_list[@]} | tr ' ' '\n' | sort | uniq -u))
 	#echo "${not_in_nav[@]}" | tr ' ' '\n'
-
-	# check if files not in nav are somewhere referenced in the "with_include" list
-	# those files are referenced and will be excluded from the not_in_nav list
-
-	# get only the filename without path component
-	not_in_nav_filename_only=($(echo "${not_in_nav[@]##*/}"))
-	#echo "${not_in_nav_filename_only[@]}" | tr ' ' '\n'
+	#exit
 
 	# run only if there are files with an include:: statement found
 	# if not found, true_not_in_nav will not be set
-	if (( ${#files_with_include[@]} )); then
-		includes_found=($(grep -hF "${not_in_nav_filename_only[@]/#/-e}" -- $(echo "${files_with_include[@]}" | tr ' ' '\n') | sed "s|include::.\/||g" | sed "s/\[[^\[]*$//" | uniq -u))
+	# ${#files_with_relative_include[@]} counts the occurrences
+	if (( ${#files_with_relative_include[@]} )); then
+		# make a list of all include lines only keeping the path/file 
+		includes_found=($(grep -w "include:." "${files_with_relative_include[@]}" | sed "s|include::.\/||g" | sed "s/\[[^\[]*$//" | uniq -u))
 		#echo "${includes_found[@]}" | tr ' ' '\n'
+		#exit
 
 		true_not_in_nav=($(echo "${not_in_nav[@]}" | tr ' ' '\n' | grep -v "${includes_found[@]/#/-e}"))
 		#echo "${true_not_in_nav[@]}" | tr ' ' '\n'
+		#exit
 	fi
 
-	# if all files found are referenced in the navigation, you do not have orhaned .adoc files
+	# if all files found are referenced in the navigation, you do not have orphaned .adoc files
 	if [ -z "$true_not_in_nav" ]; then
-		echo -e "\e[1;32mAll .adoc files are referenced in the navigation or included \e[0m"
+		echo -e "\e[1;32mNo orphaned .adoc files in pages from navigation and includes.\e[0m"
 		echo
-		echo -e "\e[1;32mNo orphans, exiting \e[0m"
-		echo
-		exit
 	fi
 
-	echo
-	echo -e "\e[1;35mFollowing files are not listed in nav.adoc or not included anywhere \e[0m"
-	echo -e "\e[1;35mCheck if this is intended \e[0m"
-	echo
-	echo "${true_not_in_nav[@]}" | tr ' ' '\n'
-	echo
+	# create a search list like: "xref:path/filename.adoc"
+	# based on all files found not referenced in the nav file or via include (like the occ commands)
+	search_list="${true_not_in_nav[@]/#/xref:}"
+	#echo "${search_list[@]}" | tr ' ' '\n'
+	#exit
 
-	# we only need to check those files which are not part of the navigation
+	# get all items which match the search list
+	xrefed=($(cat "${PAGES_FILES[@]/#/${PAGES_DIR}/}" | grep -of <(echo ${search_list[@]}| tr ' ' '\n') | sort | uniq | sed "s|xref:||"))
+	#echo ${xrefed[@]} | tr ' ' '\n'
+	#exit
 
-	# first check all non partial files
+	# now make a diff of the not in nav and the match list
+	# this is the list which is not xref'ed in any adoc file located in pages 
+	not_xrefed=($(echo ${true_not_in_nav[@]} ${xrefed[@]} | tr ' ' '\n' | sort | uniq -u))
+	#echo ${not_xrefed[@]} | tr ' ' '\n'
+	#exit
 
-	# add the relative path so it can be propely used in grep
-	checkable_files_rp="${not_partial_files[@]/#/$pages_dir/}"
-	#echo "${checkable_files_rp[@]}" | tr ' ' '\n'
-
-	# check if a file has occurences in the list of all files 
-	matches_found=($(grep -ohF "${true_not_in_nav[@]/#/-e}" -- $(echo "${checkable_files_rp[@]}" | tr ' ' '\n') | sort | uniq))
-	#echo "${matches_found[@]}" | tr ' ' '\n'
-
-	# these files look orphaned as they have no reference from anywhere
-	not_linked_in_files=($(echo ${true_not_in_nav[@]} ${matches_found[@]} | tr ' ' '\n' | sort | uniq -u))
-	#echo "${not_linked_in_files[@]}"  | tr ' ' '\n'
-
-	echo -e "\e[1;31mFollowing files are not linked anywhere and therefore orphaned \e[0m"
-	echo -e "\e[1;31mCheck if this is intended \e[0m"
-	echo
-	if (( ${#not_linked_in_files[@]} )); then
-		found=1
-		echo "${not_linked_in_files[@]}" | tr ' ' '\n'
+	if (( ${#not_xrefed[@]} )); then
+		echo
+		echo -e "\e[1;35mFollowing files are not listed in nav.adoc or included/xrefed in the pages dir.\e[0m"
+		echo -e "\e[1;35mCheck if this is intended.\e[0m"
+		echo
+		echo "${not_xrefed[@]/#/${PAGES_DIR}/}" | tr ' ' '\n'
+		echo
+		echo "You may want to check the orphan history via:"
+		echo
+		echo "git log --full-history -- full_path_file_from_above"
+		echo
+	else
+		echo -e "\e[1;32mNo orphaned .adoc files in the pages dir (xref).\e[0m"
+		echo
 	fi
 
-	# now check all partial files, partials are always referenced from non partials
+	# now check if there are orphaned partials files
 
-	# check if a file has occurences in the list of all files
-	corrected_partials=($(echo "${partial_files[@]}" | sed "s|$partials_dir\/||g"))
-	#echo "${corrected_partials[@]}" | tr ' ' '\n'
+	# get all files which have an include + family statement
+	include_list=($(cat "${PAGES_FILES[@]/#/${PAGES_DIR}/}" | grep "include::${FAMILY}" | sort | uniq))
+	#echo ${include_list[@]} | tr ' ' '\n'
+	#exit
 
-	matches_found=($(grep -ohF "${corrected_partials[@]/#/-e}" -- $(echo "${checkable_files_rp[@]}" | tr ' ' '\n') | sort | uniq))
-	#echo "${matches_found[@]}" | tr ' ' '\n'
+	# get the list of files which are included as a partial
+	partial_list=($((echo "${include_list[@]}" | tr ' ' '\n') | grep -of <(echo ${PARTIAL_FILES[@]}| tr ' ' '\n')))
+	#echo ${partial_list[@]} | tr ' ' '\n'
+	#exit
 
-	# these _partials are orphaned as they have no reference from anywhere
-	not_linked_in_files=($(echo ${corrected_partials[@]} ${matches_found[@]} | tr ' ' '\n' | sort | uniq -u))
-	#echo "${not_linked_in_files[@]}" | tr ' ' '\n'
+	# 
+	not_partial=($(echo ${PARTIAL_FILES[@]} ${partial_list[@]} | tr ' ' '\n' | sort | uniq -u))
+	#echo ${not_partial[@]}| tr ' ' '\n'
+	#exit
 
-	if (( ${#not_linked_in_files[@]} )); then
+	if (( ${#not_partial[@]} )); then
+		echo -e "\e[1;35mFollowing partial files are not linked anywhere and therefore orphaned.\e[0m"
+		echo -e "\e[1;35mCheck if this is intended.\e[0m"
 		echo
-		echo "${not_linked_in_files[@]/#/$partials_dir/}" | tr ' ' '\n'
+		echo "${not_partial[@]/#/${PARTIALS_DIR}/}" | tr ' ' '\n'
 		echo
-		exit
+		echo "You may want to check the orphan history via:"
+		echo
+		echo "git log --full-history -- full_path_file_from_above"
+		echo
+	else
+		echo -e "\e[1;32mNo orphaned .adoc files in partials dir (include).\e[0m"
+		echo
 	fi
-	if [ -z "$found" ]; then
-		echo -e "\e[1;32No orphands found \e[0m"
-		echo
-		exit
-	fi
-
 }
 
 
 while getopts ":hn:" o
 do
-    case ${o} in
-        n )
-            MANUAL_NAME=$OPTARG
-            ACTION="FIND_ORPHANS"
-            ;;
-        : )
-            echo "Invalid option: $OPTARG requires an argument" 1>&2
-            exit 1
-            ;;
-        h|* )
-            ACTION="HELP"
-            ;;
-    esac
+	case ${o} in
+		n )
+			MANUAL_NAME=$OPTARG
+			ACTION="FIND_ORPHANS"
+			;;
+		: )
+			echo "Invalid option: $OPTARG requires an argument" 1>&2
+			exit 1
+			;;
+		h|* )
+			ACTION="HELP"
+			;;
+	esac
 done
 shift $((OPTIND-1))
 
 case "$ACTION" in 
-    FIND_ORPHANS)
-        find_orphans
-        ;;
-    HELP | *)
-        usage
-        exit
-        ;;
+	FIND_ORPHANS)
+		find_orphans
+		;;
+	HELP | *)
+		usage
+		exit
+		;;
 esac
